# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arc < Formula
  desc "Terminal-first personal knowledge OS"
  homepage "https://github.com/jrniemiec/arc"
  version "0.6.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/jrniemiec/arc/releases/download/v0.6.1/arc_0.6.1_darwin_amd64.tar.gz"
    sha256 "5f9204eaf5b7213e52f419bebbf1196da1c2f9ed6731d21d1cf107c535b8e0f1"

    define_method(:install) do
      bin.install "arc"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/jrniemiec/arc/releases/download/v0.6.1/arc_0.6.1_darwin_arm64.tar.gz"
    sha256 "8cd723df1bfdf9ccc8290cc6f9af2232738d2129ee000ed51d7d3271c3a84707"

    define_method(:install) do
      bin.install "arc"
    end
  end

  test do
    system "#{bin}/arc", "--version"
  end
end
